#!/usr/bin/env node

const fs = require("fs");
const path = require("path");

const API_BASE_URL = "https://api.whenbuff.com";
const OUT_FILE = path.resolve(__dirname, "..", "Data.lua");

const TIMEZONE_OFFSETS = {
  UTC: 0,
  GMT: 0,
  BST: 60,
  CET: 60,
  CEST: 120,
  EST: -300,
  EDT: -240,
  CST: -360,
  CDT: -300,
  MST: -420,
  MDT: -360,
  PST: -480,
  PDT: -420,
};

function parseArgs(argv) {
  const args = { days: 60 };

  for (let index = 2; index < argv.length; index += 1) {
    const arg = argv[index];
    if (arg === "--days" && argv[index + 1]) {
      args.days = Number(argv[index + 1]);
      index += 1;
    }
  }

  if (!Number.isFinite(args.days) || args.days < 1) {
    throw new Error("--days must be a positive number");
  }

  return args;
}

function formatApiDate(date) {
  const day = String(date.getDate()).padStart(2, "0");
  const month = String(date.getMonth() + 1).padStart(2, "0");
  const year = date.getFullYear();
  return `${day}/${month}/${year}`;
}

function parseBuffTimestamp(buffDate, timezone) {
  const match = /^(\d{2})\/(\d{2})\/(\d{4})-(\d{2}):(\d{2})$/.exec(buffDate);
  if (!match) {
    throw new Error(`Unexpected buff_date format: ${buffDate}`);
  }

  const [, day, month, year, hour, minute] = match.map(Number);
  const offsetMinutes = TIMEZONE_OFFSETS[timezone];
  if (offsetMinutes === undefined) {
    throw new Error(`Unsupported server timezone: ${timezone}`);
  }

  const utcMs = Date.UTC(year, month - 1, day, hour, minute) - offsetMinutes * 60 * 1000;
  return Math.floor(utcMs / 1000);
}

function luaString(value) {
  return `"${String(value ?? "")
    .replace(/\\/g, "\\\\")
    .replace(/"/g, '\\"')
    .replace(/\r/g, "\\r")
    .replace(/\n/g, "\\n")}"`;
}

function luaBoolean(value) {
  return value ? "true" : "false";
}

async function getJson(url) {
  const response = await fetch(url, {
    headers: {
      "Cache-Control": "no-cache",
      Pragma: "no-cache",
    },
  });

  if (!response.ok) {
    throw new Error(`${url} returned ${response.status}`);
  }

  return response.json();
}

function buffToLua(buff, server) {
  const faction = buff.buff_faction === "both" ? "both" : buff.buff_faction;
  const timestamp = parseBuffTimestamp(buff.buff_date, server.server_timezone);

  return [
    "      {",
    `        type = ${luaString(buff.buff_type)},`,
    `        faction = ${luaString(faction)},`,
    `        date = ${luaString(buff.buff_date)},`,
    `        timestamp = ${timestamp},`,
    `        guild = ${luaString(buff.buff_guild)},`,
    `        notes = ${luaString(buff.buff_notes || "")},`,
    `        badge = ${luaBoolean(buff.badge)},`,
    "      },",
  ].join("\n");
}

function renderLua({ generatedAt, servers, buffsByServer, days }) {
  const lines = [
    "-- This file is generated by the WhenBuff data updater. Do not edit by hand.",
    "WhenBuffInGame_Data = {",
    `  generatedAt = ${luaString(generatedAt)},`,
    `  source = ${luaString(API_BASE_URL)},`,
    `  lookaheadDays = ${days},`,
    "  serverOrder = {",
  ];

  for (const server of servers) {
    lines.push(`    ${luaString(server.server_name)},`);
  }

  lines.push("  },");
  lines.push("  servers = {");

  for (const server of servers) {
    const buffs = buffsByServer.get(server.server_name) || [];
    lines.push(`    [${luaString(server.server_name)}] = {`);
    lines.push(`      region = ${luaString(server.server_region)},`);
    lines.push(`      timezone = ${luaString(server.server_timezone)},`);
    lines.push(`      discordName = ${luaString(server.server_discord_name || "")},`);
    lines.push(`      discordUrl = ${luaString(server.server_discord_url || "")},`);
    lines.push("      buffs = {");

    for (const buff of buffs) {
      lines.push(buffToLua(buff, server));
    }

    lines.push("      },");
    lines.push("    },");
  }

  lines.push("  },");
  lines.push("}");
  lines.push("");

  return lines.join("\n");
}

async function main() {
  const args = parseArgs(process.argv);
  const generatedAt = new Date().toISOString();
  const today = new Date();
  const fromDate = new Date(today);
  fromDate.setDate(today.getDate() - 1);
  const toDate = new Date(today);
  toDate.setDate(today.getDate() + args.days + 1);

  const servers = await getJson(`${API_BASE_URL}/servers`);
  servers.sort((a, b) => a.server_name.localeCompare(b.server_name));

  const buffsByServer = new Map();
  const from = encodeURIComponent(formatApiDate(fromDate));
  const to = encodeURIComponent(formatApiDate(toDate));

  for (const server of servers) {
    const url = `${API_BASE_URL}/buffs?server=${encodeURIComponent(server.server_name)}&from_date=${from}&to_date=${to}`;
    const buffs = await getJson(url);
    buffs.sort((a, b) => parseBuffTimestamp(a.buff_date, server.server_timezone) - parseBuffTimestamp(b.buff_date, server.server_timezone));
    buffsByServer.set(server.server_name, buffs);
    console.log(`${server.server_name}: ${buffs.length} buffs`);
  }

  const lua = renderLua({ generatedAt, servers, buffsByServer, days: args.days });
  fs.writeFileSync(OUT_FILE, lua, "utf8");
  console.log(`Wrote ${OUT_FILE}`);
}

main().catch((error) => {
  console.error(error);
  process.exitCode = 1;
});