param(
    [ValidateRange(1, 365)]
    [int] $Days = 60,

    [string] $OutputPath = (Join-Path (Split-Path -Parent $PSScriptRoot) "Data.lua")
)

$ErrorActionPreference = "Stop"

$ApiBaseUrl = "https://api.whenbuff.com"
$TimezoneOffsets = @{
    UTC = 0
    GMT = 0
    BST = 60
    CET = 60
    CEST = 120
    EST = -300
    EDT = -240
    CST = -360
    CDT = -300
    MST = -420
    MDT = -360
    PST = -480
    PDT = -420
}

function Format-ApiDate {
    param([datetime] $Date)
    return $Date.ToString("dd/MM/yyyy", [System.Globalization.CultureInfo]::InvariantCulture)
}

function Invoke-WhenBuffJson {
    param([string] $Url)

    return Invoke-RestMethod -Uri $Url -Headers @{
        "Cache-Control" = "no-cache"
        "Pragma" = "no-cache"
    }
}

function ConvertTo-BuffTimestamp {
    param(
        [string] $BuffDate,
        [string] $Timezone
    )

    if ($BuffDate -notmatch "^(\d{2})/(\d{2})/(\d{4})-(\d{2}):(\d{2})$") {
        throw "Unexpected buff_date format: $BuffDate"
    }

    if (-not $TimezoneOffsets.ContainsKey($Timezone)) {
        throw "Unsupported server timezone: $Timezone"
    }

    $day = [int] $Matches[1]
    $month = [int] $Matches[2]
    $year = [int] $Matches[3]
    $hour = [int] $Matches[4]
    $minute = [int] $Matches[5]
    $offsetMinutes = [int] $TimezoneOffsets[$Timezone]

    $utcTime = [datetime]::SpecifyKind(
        [datetime]::new($year, $month, $day, $hour, $minute, 0),
        [System.DateTimeKind]::Utc
    ).AddMinutes(-$offsetMinutes)
    $epoch = [datetime]::SpecifyKind([datetime] "1970-01-01T00:00:00", [System.DateTimeKind]::Utc)

    return [int64] [math]::Floor(($utcTime - $epoch).TotalSeconds)
}

function ConvertTo-LuaString {
    param([object] $Value)

    $text = if ($null -eq $Value) { "" } else { [string] $Value }
    $text = $text.Replace("\", "\\")
    $text = $text.Replace("""", "\""")
    $text = $text.Replace("`r", "\r")
    $text = $text.Replace("`n", "\n")
    return """" + $text + """"
}

function ConvertTo-LuaBoolean {
    param([object] $Value)
    if ($Value) {
        return "true"
    }

    return "false"
}

function ConvertTo-BuffLua {
    param(
        [object] $Buff,
        [object] $Server
    )

    $faction = if ($Buff.buff_faction -eq "both") { "both" } else { $Buff.buff_faction }
    $timestamp = ConvertTo-BuffTimestamp -BuffDate $Buff.buff_date -Timezone $Server.server_timezone

    return @(
        "      {",
        "        type = $(ConvertTo-LuaString $Buff.buff_type),",
        "        faction = $(ConvertTo-LuaString $faction),",
        "        date = $(ConvertTo-LuaString $Buff.buff_date),",
        "        timestamp = $timestamp,",
        "        guild = $(ConvertTo-LuaString $Buff.buff_guild),",
        "        notes = $(ConvertTo-LuaString $Buff.buff_notes),",
        "        badge = $(ConvertTo-LuaBoolean $Buff.badge),",
        "      },"
    ) -join "`n"
}

function ConvertTo-DataLua {
    param(
        [string] $GeneratedAt,
        [array] $Servers,
        [hashtable] $BuffsByServer
    )

    $lines = [System.Collections.Generic.List[string]]::new()
    $lines.Add("-- This file is generated by tools/update-data.ps1. Do not edit by hand.")
    $lines.Add("WhenBuffInGame_Data = {")
    $lines.Add("  generatedAt = $(ConvertTo-LuaString $GeneratedAt),")
    $lines.Add("  source = $(ConvertTo-LuaString $ApiBaseUrl),")
    $lines.Add("  lookaheadDays = $Days,")
    $lines.Add("  serverOrder = {")

    foreach ($server in $Servers) {
        $lines.Add("    $(ConvertTo-LuaString $server.server_name),")
    }

    $lines.Add("  },")
    $lines.Add("  servers = {")

    foreach ($server in $Servers) {
        $buffs = @($BuffsByServer[$server.server_name])
        $lines.Add("    [$(ConvertTo-LuaString $server.server_name)] = {")
        $lines.Add("      region = $(ConvertTo-LuaString $server.server_region),")
        $lines.Add("      timezone = $(ConvertTo-LuaString $server.server_timezone),")
        $lines.Add("      discordName = $(ConvertTo-LuaString $server.server_discord_name),")
        $lines.Add("      discordUrl = $(ConvertTo-LuaString $server.server_discord_url),")
        $lines.Add("      buffs = {")

        foreach ($buff in $buffs) {
            $lines.Add((ConvertTo-BuffLua -Buff $buff -Server $server))
        }

        $lines.Add("      },")
        $lines.Add("    },")
    }

    $lines.Add("  },")
    $lines.Add("}")
    $lines.Add("")

    return $lines -join "`n"
}

$generatedAt = [datetime]::UtcNow.ToString("yyyy-MM-ddTHH:mm:ss.fffZ", [System.Globalization.CultureInfo]::InvariantCulture)
$today = Get-Date
$fromDate = $today.AddDays(-1)
$toDate = $today.AddDays($Days + 1)
$from = [uri]::EscapeDataString((Format-ApiDate $fromDate))
$to = [uri]::EscapeDataString((Format-ApiDate $toDate))

$servers = @((Invoke-WhenBuffJson "$ApiBaseUrl/servers")) | Sort-Object server_name
$buffsByServer = @{}

foreach ($server in $servers) {
    $serverName = [string] $server.server_name
    $url = "$ApiBaseUrl/buffs?server=$([uri]::EscapeDataString($serverName))&from_date=$from&to_date=$to"
    $rawBuffs = @((Invoke-WhenBuffJson $url))
    $buffs = @($rawBuffs | Where-Object { $_ -and $_.buff_date } | Sort-Object @{
        Expression = { ConvertTo-BuffTimestamp -BuffDate $_.buff_date -Timezone $server.server_timezone }
    })
    $buffsByServer[$serverName] = $buffs
    Write-Host "${serverName}: $($buffs.Count) buffs"
}

$outputDirectory = Split-Path -Parent $OutputPath
if ($outputDirectory -and -not (Test-Path -LiteralPath $outputDirectory)) {
    New-Item -ItemType Directory -Path $outputDirectory | Out-Null
}

$lua = ConvertTo-DataLua -GeneratedAt $generatedAt -Servers $servers -BuffsByServer $buffsByServer
$utf8NoBom = [System.Text.UTF8Encoding]::new($false)
[System.IO.File]::WriteAllText($OutputPath, $lua, $utf8NoBom)
Write-Host "Wrote $OutputPath"